workflows:
    orocrm_contact_us_contact_request:
        label:   'Contact Request'
        entity:   OroCRM\Bundle\ContactUsBundle\Entity\ContactRequest
        entity_attribute: request
        start_step: open
        steps:
            open:
                label: 'Open'
                order: 10
                allowed_transitions:
                    - convert_to_opportunity
                    - convert_to_lead
                    - resolve
            resolved:
                label: 'Resolved'
                order: 40
            converted_to_opportunity:
                label: 'Converted to opportunity'
                order: 30
            converted_to_lead:
                label: 'Converted to lead'
                order: 30

        attributes:
            # opportunity attributes
            opportunity_name:
                label: 'Opportunity name'
                type:   string
            opportunity_owner:
                label: 'Owner'
                type:  entity
                options:
                    class: Oro\Bundle\UserBundle\Entity\User
            opportunity_budget:
                label: 'Budget amount'
                type:  float

            # lead attributes
            lead_owner:
                label: 'Owner'
                type:  entity
                options:
                    class: Oro\Bundle\UserBundle\Entity\User
            lead_name:
                label:    'Lead name'
                type:      string
            lead_first_name:
                label:    'First name'
                type:      string
            lead_last_name:
                label:    'Last name'
                type:      string
            lead_phone:
                label:    'Phone number'
                type:     string
            lead_email:
                label:    'Email'
                type:     string

            # Other workflow attributes
            feedback:
                label:        'Feedback'
                type:          string
                property_path: request.feedback
            account:
                label:  'Account'
                type:   entity
                options:
                    class: OroCRM\Bundle\AccountBundle\Entity\Account
            contact:
                label:   'Contact'
                type:     entity
                options:
                    class: OroCRM\Bundle\ContactBundle\Entity\Contact
            dataChannel:
                property_path: request.dataChannel
        transitions:
            convert_to_opportunity:
                label:    'Convert to opportunity'
                step_to:  converted_to_opportunity
                is_start: true
                is_unavailable_hidden: true
                acl_resource: orocrm_sales_opportunity_create
                frontend_options:
                    icon: 'icon-usd'
                transition_definition: convert_to_opportunity_definition
                form_options:
                    attribute_fields:
                        opportunity_name:
                            form_type: text
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        opportunity_owner:
                            form_type: oro_user_select
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        contact:
                            form_type: orocrm_contact_select
                            options:
                                required: false
                                label:    'Contact'
                        opportunity_budget:
                            form_type: oro_money
                            options:
                                required: false
                        feedback:
                            form_type: textarea
                            options:
                                required: false
                    init_actions:
                        - '@assign_active_user': $opportunity_owner
                        - '@format_name':
                            attribute: $opportunity_name
                            object:    $request
            convert_to_lead:
                label:     'Convert to lead'
                step_to:   converted_to_lead
                is_start:  true
                is_unavailable_hidden: true
                acl_resource: orocrm_sales_lead_create
                frontend_options:
                    icon: 'icon-phone-sign'
                transition_definition: convert_to_lead_definition
                form_options:
                    attribute_fields:
                        lead_owner:
                            form_type: oro_user_select
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        contact:
                            form_type: orocrm_contact_select
                            options:
                                required: false
                                label:    'Contact'
                        lead_name:
                            form_type: text
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        lead_first_name:
                            form_type: text
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        lead_last_name:
                            form_type: text
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        lead_phone:
                            form_type: text
                            options:
                                required: false
                        lead_email:
                            form_type: oro_email_email_address
                            options:
                                required: false
                                constraints:
                                   - Email: ~
                        feedback:
                            form_type: textarea
                            options:
                                required: false
                    init_actions:
                        - '@assign_active_user': $lead_owner
                        - '@format_name':
                            attribute: $lead_name
                            object:    $request
                        - '@assign_value': [$lead_first_name, $request.firstName]
                        - '@assign_value': [$lead_last_name,  $request.lastName]
                        - '@assign_value': [$lead_phone,  $request.phone]
                        - '@assign_value': [$lead_email,  $request.emailAddress]
            resolve:
                label:      'Resolve'
                step_to:    resolved
                is_start:   true
                is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-check'
                transition_definition: resolve_definition
                form_options:
                    attribute_fields:
                        feedback:
                            form_type: textarea
                            options:
                                required: false

        transition_definitions:
            __start___definition:
                pre_conditions:
                    '@not_empty': $request.id
            convert_to_opportunity_definition:
                pre_conditions:
                    '@channel_entity_availiable': [$dataChannel, ['OroCRM\Bundle\SalesBundle\Entity\Opportunity']]
                conditions:
                    '@and':
                        - '@not_empty':
                            parameters: $opportunity_name
                            message:    'Opportunity name must be set'
                        - '@not_empty':
                            parameters: $opportunity_owner
                            message:    'Owner must be set'
                post_actions:
                    - '@request_enum_entity':
                        enum_code: opportunity_status
                        identifier:  'in_progress'
                        attribute:   $.result.opportunity_status
                    - '@create_entity': # create an opportunity
                        class:     OroCRM\Bundle\SalesBundle\Entity\Opportunity
                        attribute: $request.opportunity
                        data:
                            name:         $opportunity_name
                            owner:        $opportunity_owner
                            budgetAmount: $opportunity_budget
                            contact:      $contact
                            status:       $.result.opportunity_status
                            notes:        $feedback
                            dataChannel:  $dataChannel

            convert_to_lead_definition:
                pre_conditions:
                    '@channel_entity_availiable': [$dataChannel, ['OroCRM\Bundle\SalesBundle\Entity\Lead']]
                conditions:
                    '@and':
                        - '@not_empty':
                            parameters: $lead_name
                            message:    'Lead name must be set'
                        - '@not_empty':
                            parameters: $lead_first_name
                            message:    'Lead first name must be set'
                        - '@not_empty':
                            parameters: $lead_last_name
                            message:    'Lead last name must be set'
                        - '@not_empty':
                            parameters: $lead_owner
                            message:    'Lead must be set'
                post_actions:
                    - '@request_enum_entity':
                        enum_code: lead_status
                        identifier:  'new'
                        attribute:   $.result.lead_status
                    - '@create_entity': # create a lead
                        class:     OroCRM\Bundle\SalesBundle\Entity\Lead
                        attribute: $request.lead
                        data:
                            name:         $lead_name
                            firstName:    $lead_first_name
                            lastName:     $lead_last_name
                            owner:        $lead_owner
                            phoneNumber:  $lead_phone
                            email:        $lead_email
                            contact:      $contact
                            status:       $.result.lead_status
                            notes:        $feedback
                            dataChannel:  $dataChannel
            resolve_definition:
                pre_conditions:
                    '@not_empty': $request.id
